### ISSUE TITLE
[Bug] Cohen's w and Cramer's V default to equal proportions and ignore entered expected values 

### ISSUE THREAD

**Issue by charlottetate77** [easystats/effectsize#352]
#I noticed an issue when trying to request either Cohen's w or Cramer's V for the one-way chi-square using either the effectsize(), cramers_v(), or cohens_w() functions on the baseR chisq.test() function inputs. 

The issue is that all effect size functions appear to default to equal proportions for the expected values and **ignore entered expected values by the user** (which, of course, are necessary for use in the difference-from-comparison form of the one-way tables).

Here is a reproducible example using entered data:

+++++++ (begin example)

`#creating the data`
`>observed.dfc = c(119,61)`
`>expected.dfc = c(0.165, 0.835)`

`#checking the data properties`
`>sum(observed.dfc)`
`[1] 180`
`>sum(expected.dfc)`
`[1] 1`

`#running the chi-square test to show that the baseR function works`
`> chisq.test(x = observed.dfc, p = expected.dfc)`

`	Chi-squared test for given probabilities`

`data:  observed2.dfc`
`X-squared = 321.56, df = 1, p-value < 2.2e-16`

`#now running the cramers_v() function on the baseR code`
`> cramers_v(chisq.test(x = observed.dfc, p = expected.dfc))`
`      V  |       95% CI`
`-------------------`
`  0.32 | [0.18, 0.47]`

+++++++(end example)

However, the correct answer is V = 1.34 [as sqrt((321.65/180)/(2-1))].

When I input the equal proportions form of the baseR chi-square test, I get the values that the cramers_v() function is using and thus returning:
`> chisq.test(x = observed2.dfc)`

`	Chi-squared test for given probabilities`

`data:  observed2.dfc`
`X-squared = 18.689, df = 1, p-value = 1.539e-05`

Here, the answer really is 0.32 [as sqrt((18.689/180)/(2-1))], which leads me to believe that the effect size functions as built are ignoring the entered expected values by a user and defaulting to equal proportions.

This seems like it should be fixed.

P.S. This is my first issue-submission, so sorry if it's verbose and unconventional with respect to seasoned posters.
P.P.S. The work around I found is to use the chisq_to_cramers_v() function and input the necessary information, which returns the correct answer for the entered expected values.

**Comment by mattansb** [comment]
@charlottetate77 Thanks for this catch!

Should be fixed now (this was a hard one to hunt down...)

``` r
library(effectsize)

observed.dfc <- c(119,61)
expected.dfc <- c(0.165, 0.835)

x <- chisq.test(x = observed.dfc, p = expected.dfc)


effectsize(x, type = "v")
#> Cramer's V |       95% CI
#> -------------------------
#> 1.34       | [1.19, 1.48]
cramers_v(x)
#> Cramer's V |       95% CI
#> -------------------------
#> 1.34       | [1.19, 1.48]
cramers_v(x = observed.dfc, p = expected.dfc)
#> Cramer's V |       95% CI
#> -------------------------
#> 1.34       | [1.19, 1.48]
```

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by charlottetate77** [comment]
Thanks for the fix! How long before it appears in a downloadable package update? (I checked RStudio Cloud but the bug still remains there.)

**Comment by IndrajeetPatil** [comment]
It might be awhile (~ a month).

For now, you can just download the GitHub version:

```r
remotes::install_github("easystats/effectsize")
```
