### ISSUE TITLE
Where do the values come from?

### ISSUE THREAD

**Issue by mattansb** [easystats/effectsize#529]
### Discussed in https://github.com/easystats/effectsize/discussions/528

<div type='discussions-op-text'>

<sup>Originally posted by **chaohanch** October 27, 2022</sup>
Dear developers, I was looking for a way to get eta-squared from an _emmeans_ result. This package looks promising. But as I go through this page (https://easystats.github.io/effectsize/articles/from_test_statistics.html), I'm confused about why the values entering the _t_to_eta2_ function do not match the _emmeans_ output (the screenshot below). I'm wondering where these t values and the df_error value come from. Thank you!
![image](https://user-images.githubusercontent.com/32816513/198157378-8777b51b-0fec-44da-9bf9-2f50e675cd7b.png)
</div>

**Comment by mattansb** [comment]
This was a mistake probably left over from a previous version of the vignette. Fixed now

**Comment by HanZhang-psych** [comment]
Reopening this issue as the values in the In Contrast Analysis section and the Within-Subject Contrasts are not fixed.
